name: srichki
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  # icons_plus: ^3.0.0
  audioplayers: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/background.jpg
    - assets/sun.png
    - assets/back_arrow.png
    - assets/home_icon.png
    - assets/predmeti/agal.jpg
    - assets/predmeti/agne.jpg
    - assets/predmeti/ananas.jpg
    - assets/predmeti/angel.jpg
    - assets/predmeti/avtobus.jpg
    - assets/predmeti/baloni.jpg
    - assets/predmeti/banan.jpg
    - assets/predmeti/barbaran.jpg
    - assets/predmeti/biskvita.jpg
    - assets/predmeti/blizalka.jpg
    - assets/predmeti/bonbon.jpg
    - assets/predmeti/bos.jpg
    - assets/predmeti/car.jpg
    - assets/predmeti/chai.jpg
    - assets/predmeti/chorap.jpg
    - assets/predmeti/cigulka.jpg
    - assets/predmeti/cip.jpg
    - assets/predmeti/cvete.jpg
    - assets/predmeti/darvo.jpg
    - assets/predmeti/delfin.jpg
    - assets/predmeti/dim.jpg
    - assets/predmeti/dinq.jpg
    - assets/predmeti/elen.jpg
    - assets/predmeti/elha.jpg
    - assets/predmeti/fakla.jpg
    - assets/predmeti/far.jpg
    - assets/predmeti/fazan.jpg
    - assets/predmeti/gaba.jpg
    - assets/predmeti/galab.jpg
    - assets/predmeti/garaj.jpg
    - assets/predmeti/garderob.jpg
    - assets/predmeti/garvan.jpg
    - assets/predmeti/gaz.jpg
    - assets/predmeti/greben.jpg
    - assets/predmeti/grozde.jpg
    - assets/predmeti/halm.jpg
    - assets/predmeti/hapche.jpg
    - assets/predmeti/hlqb.jpg
    - assets/predmeti/horoskop.jpg
    - assets/predmeti/ioga.jpg
    - assets/predmeti/iskra.jpg
    - assets/predmeti/izgrev.jpg
    - assets/predmeti/jaba.jpg
    - assets/predmeti/jalto.jpg
    - assets/predmeti/jele.jpg
    - assets/predmeti/jirav.jpg
    - assets/predmeti/kalinka.jpg
    - assets/predmeti/kalvach.jpg
    - assets/predmeti/kamak.jpg
    - assets/predmeti/kartof.jpg
    - assets/predmeti/kashta.jpg
    - assets/predmeti/katerica.jpg
    - assets/predmeti/kenguru.jpg
    - assets/predmeti/kilim.jpg
    - assets/predmeti/kitara.jpg
    - assets/predmeti/kniga.jpg
    - assets/predmeti/kofa.jpg
    - assets/predmeti/kola.jpg
    - assets/predmeti/kolelo.jpg
    - assets/predmeti/kon.jpg
    - assets/predmeti/korab.jpg
    - assets/predmeti/kotka.jpg
    - assets/predmeti/koza.jpg
    - assets/predmeti/kuche.jpg
    - assets/predmeti/kufar.jpg
    - assets/predmeti/kutiq.jpg
    - assets/predmeti/lebed.jpg
    - assets/predmeti/lisica.jpg
    - assets/predmeti/lopata.jpg
    - assets/predmeti/lovec.jpg
    - assets/predmeti/luk.jpg
    - assets/predmeti/luna.jpg
    - assets/predmeti/maimuna.jpg
    - assets/predmeti/masa.jpg
    - assets/predmeti/mechka.jpg
    - assets/predmeti/midi.jpg
    - assets/predmeti/mikrovalnova.jpg
    - assets/predmeti/mishka.jpg
    - assets/predmeti/molivnik.jpg
    - assets/predmeti/muha.jpg
    - assets/predmeti/nar.jpg
    - assets/predmeti/nojica.jpg
    - assets/predmeti/nosht.jpg
    - assets/predmeti/oblak.jpg
    - assets/predmeti/ochila.jpg
    - assets/predmeti/ohluv.jpg
    - assets/predmeti/oktopod.jpg
    - assets/predmeti/orel.jpg
    - assets/predmeti/pamuk.jpg
    - assets/predmeti/pan.jpg
    - assets/predmeti/pchela.jpg
    - assets/predmeti/peperuda.jpg
    - assets/predmeti/pero.png
    - assets/predmeti/petel.jpg
    - assets/predmeti/pica.jpg
    - assets/predmeti/pismo.jpg
    - assets/predmeti/plasht.jpg
    - assets/predmeti/podarak.jpg
    - assets/predmeti/pola.jpg
    - assets/predmeti/ponichka.jpg
    - assets/predmeti/pop.jpg
    - assets/predmeti/portokal.jpg
    - assets/predmeti/prag.jpg
    - assets/predmeti/prast.jpg
    - assets/predmeti/prejda.jpg
    - assets/predmeti/qbalka.jpg
    - assets/predmeti/qgoda.jpg
    - assets/predmeti/qice.jpg
    - assets/predmeti/qzovech.jpg
    - assets/predmeti/rak.jpg
    - assets/predmeti/raka.jpg
    - assets/predmeti/raketa.jpg
    - assets/predmeti/ranica.jpg
    - assets/predmeti/riba.jpg
    - assets/predmeti/roza.jpg
    - assets/predmeti/samolet.jpg
    - assets/predmeti/sarf.jpg
    - assets/predmeti/shal.jpg
    - assets/predmeti/shapka.jpg
    - assets/predmeti/shisharka.jpg
    - assets/predmeti/shtarkel.jpg
    - assets/predmeti/shtit.jpg
    - assets/predmeti/shtori.jpg
    - assets/predmeti/slache.jpg
    - assets/predmeti/sladoled.jpg
    - assets/predmeti/smqh.avif
    - assets/predmeti/sok.jpg
    - assets/predmeti/stena.jpg
    - assets/predmeti/strah.jpg
    - assets/predmeti/taralej.jpg
    - assets/predmeti/teniska.jpg
    - assets/predmeti/testo.jpg
    - assets/predmeti/tigar.jpg
    - assets/predmeti/tikvi.jpg
    - assets/predmeti/topka.jpg
    - assets/predmeti/torta.jpg
    - assets/predmeti/toster.jpg
    - assets/predmeti/uchilishte.jpg
    - assets/predmeti/urgan.jpg
    - assets/predmeti/usta.jpg
    - assets/predmeti/utiq.jpg
    - assets/predmeti/valna.jpg
    - assets/predmeti/voda.jpg
    - assets/predmeti/vrata.jpg
    - assets/predmeti/zaek.jpg
    - assets/predmeti/zar.jpg
    - assets/predmeti/zebra.jpg
    - assets/predmeti/cheresha.jpg
    - assets/bukvi/a.png
    - assets/bukvi/aa.png
    - assets/bukvi/aa_a.png
    - assets/bukvi/b.png
    - assets/bukvi/c.png
    - assets/bukvi/ch.png
    - assets/bukvi/d.png
    - assets/bukvi/e.png
    - assets/bukvi/f.png
    - assets/bukvi/g.png
    - assets/bukvi/h.png
    - assets/bukvi/i.png
    - assets/bukvi/ii.png
    - assets/bukvi/jh.png
    - assets/bukvi/k.png
    - assets/bukvi/l.png
    - assets/bukvi/m.png
    - assets/bukvi/n.png
    - assets/bukvi/o.png
    - assets/bukvi/p.png
    - assets/bukvi/q.png
    - assets/bukvi/r.png
    - assets/bukvi/s.png
    - assets/bukvi/sh.png
    - assets/bukvi/sht.png
    - assets/bukvi/t.png
    - assets/bukvi/u.png
    - assets/bukvi/uu.png
    - assets/bukvi/v.png
    - assets/bukvi/z.png
    - assets/backgrounds/bg1.png
    - assets/backgrounds/bg2.png
    - assets/backgrounds/bg3.jpg
    - assets/backgrounds/bg4.jpg
    - assets/bukvibg/A.png
    - assets/bukvibg/Б.png
    - assets/bukvibg/В.png
    - assets/bukvibg/Г.png
    - assets/bukvibg/Д.png
    - assets/bukvibg/Е.png
    - assets/bukvibg/Ж.png
    - assets/bukvibg/З.png
    - assets/bukvibg/И.png
    - assets/bukvibg/Й.png
    - assets/bukvibg/К.png
    - assets/bukvibg/Л.png
    - assets/bukvibg/М.png
    - assets/bukvibg/Н.png
    - assets/bukvibg/О.png
    - assets/bukvibg/П.png
    - assets/bukvibg/Р.png
    - assets/bukvibg/С.png
    - assets/bukvibg/Т.png
    - assets/bukvibg/У.png
    - assets/bukvibg/Ф.png
    - assets/bukvibg/Х.png
    - assets/bukvibg/Ц.png
    - assets/bukvibg/Ч.png
    - assets/bukvibg/Ш.png
    - assets/bukvibg/Щ.png
    - assets/bukvibg/Ъ.png
    - assets/bukvibg/Ь.png
    - assets/bukvibg/Ю.png
    - assets/bukvibg/Я.png
    - assets/sun2.png
    - assets/arrow.png
    - assets/sound/agal.mp3
    - assets/sound/agne.mp3
    - assets/sound/ananas.mp3
    - assets/sound/angel.mp3
    - assets/sound/avtobus.mp3
    - assets/sound/baloni.mp3
    - assets/sound/banan.mp3
    - assets/sound/barbaran.mp3
    - assets/sound/biskvita.mp3
    - assets/sound/blizalka.mp3
    - assets/sound/bonbon.mp3
    - assets/sound/bos.mp3
    - assets/sound/car.mp3
    - assets/sound/chai.mp3
    - assets/sound/chorap.mp3
    - assets/sound/cigulka.mp3
    - assets/sound/cip.mp3
    - assets/sound/cvete.mp3
    - assets/sound/darvo.mp3
    - assets/sound/delfin.mp3
    - assets/sound/dim.mp3
    - assets/sound/dinq.mp3
    - assets/sound/elen.mp3
    - assets/sound/elha.mp3
    - assets/sound/fakla.mp3
    - assets/sound/far.mp3
    - assets/sound/fazan.mp3
    - assets/sound/gaba.mp3
    - assets/sound/galab.mp3
    - assets/sound/garaj.mp3
    - assets/sound/garderob.mp3
    - assets/sound/garvan.mp3
    - assets/sound/gaz.mp3
    - assets/sound/greben.mp3
    - assets/sound/grozde.mp3
    - assets/sound/halm.mp3
    - assets/sound/hapche.mp3
    - assets/sound/hlqb.mp3
    - assets/sound/horoskop.mp3
    - assets/sound/ioga.mp3
    - assets/sound/iskra.mp3
    - assets/sound/izgrev.mp3
    - assets/sound/jaba.mp3
    - assets/sound/jalto.mp3
    - assets/sound/jele.mp3
    - assets/sound/jirav.mp3
    - assets/sound/kalinka.mp3
    - assets/sound/kalvach.mp3
    - assets/sound/kamak.mp3
    - assets/sound/kartof.mp3
    - assets/sound/kashta.mp3
    - assets/sound/katerica.mp3
    - assets/sound/kenguru.mp3
    - assets/sound/kilim.mp3
    - assets/sound/kitara.mp3
    - assets/sound/kniga.mp3
    - assets/sound/kofa.mp3
    - assets/sound/kola.mp3
    - assets/sound/kolelo.mp3
    - assets/sound/kon.mp3
    - assets/sound/korab.mp3
    - assets/sound/kotka.mp3
    - assets/sound/koza.mp3
    - assets/sound/kuche.mp3
    - assets/sound/kufar.mp3
    - assets/sound/kutiq.mp3
    - assets/sound/lebed.mp3
    - assets/sound/lisica.mp3
    - assets/sound/lopata.mp3
    - assets/sound/lovec.mp3
    - assets/sound/luk.mp3
    - assets/sound/luna.mp3
    - assets/sound/maimuna.mp3
    - assets/sound/masa.mp3
    - assets/sound/mechka.mp3
    - assets/sound/midi.mp3
    - assets/sound/mishka.mp3
    - assets/sound/molivnik.mp3
    - assets/sound/muha.mp3
    - assets/sound/nar.mp3
    - assets/sound/nojica.mp3
    - assets/sound/nosht.mp3
    - assets/sound/oblak.mp3
    - assets/sound/ochila.mp3
    - assets/sound/ohluv.mp3
    - assets/sound/oktopod.mp3
    - assets/sound/orel.mp3
    - assets/sound/pamuk.mp3
    - assets/sound/pan.mp3
    - assets/sound/pchela.mp3
    - assets/sound/peperuda.mp3
    - assets/sound/pero.mp3
    - assets/sound/petel.mp3
    - assets/sound/pica.mp3
    - assets/sound/pismo.mp3
    - assets/sound/plasht.mp3
    - assets/sound/podarak.mp3
    - assets/sound/pola.mp3
    - assets/sound/ponichka.mp3
    - assets/sound/pop.mp3
    - assets/sound/portokal.mp3
    - assets/sound/prag.mp3
    - assets/sound/prast.mp3
    - assets/sound/prejda.mp3
    - assets/sound/qbalka.mp3
    - assets/sound/qgoda.mp3
    - assets/sound/qice.mp3
    - assets/sound/qzovech.mp3
    - assets/sound/rak.mp3
    - assets/sound/raka.mp3
    - assets/sound/raketa.mp3
    - assets/sound/ranica.mp3
    - assets/sound/riba.mp3
    - assets/sound/roza.mp3
    - assets/sound/samolet.mp3
    - assets/sound/sarf.mp3
    - assets/sound/shal.mp3
    - assets/sound/shapka.mp3
    - assets/sound/shisharka.mp3
    - assets/sound/shtarkel.mp3
    - assets/sound/shtit.mp3
    - assets/sound/shtori.mp3
    - assets/sound/slache.mp3
    - assets/sound/sladoled.mp3
    - assets/sound/sok.mp3
    - assets/sound/stena.mp3
    - assets/sound/strah.mp3
    - assets/sound/taralej.mp3
    - assets/sound/teniska.mp3
    - assets/sound/testo.mp3
    - assets/sound/tigar.mp3
    - assets/sound/tikvi.mp3
    - assets/sound/topka.mp3
    - assets/sound/torta.mp3
    - assets/sound/toster.mp3
    - assets/sound/uchilishte.mp3
    - assets/sound/urgan.mp3
    - assets/sound/usta.mp3
    - assets/sound/valna.mp3
    - assets/sound/voda.mp3
    - assets/sound/vrata.mp3
    - assets/sound/zaek.mp3
    - assets/sound/zar.mp3
    - assets/sound/zebra.mp3
    - assets/sound/cheresha.mp3
    - assets/sound/testedno.mp3
    - assets/sound/testdve.mp3
    - assets/sound/testtri.mp3
    - assets/sound/chalga.mp3

  fonts:
    - family: kids
      fonts:
        - asset: assets/fonts/kids.ttf