Map<String, dynamic> dumi = {
  'Автобус': [
    7,
    'predmeti/avtobus.jpg',
    'bukvi/a.png',
    'sound/avtobus.mp3',
  ],
  'Агне': [
    4,
    'predmeti/agne.jpg',
    'bukvi/a.png',
    'sound/agne.mp3',
  ],
  'Ананас': [
    6,
    'predmeti/ananas.jpg',
    'bukvi/a.png',
    'sound/ananas.mp3',
  ],
  'Ангел': [
    5,
    'predmeti/angel.jpg',
    'bukvi/a.png',
    'sound/angel.mp3',
  ],
  'Балони': [
    6,
    'predmeti/baloni.jpg',
    'bukvi/b.png',
    'sound/baloni.mp3',
  ],
  'Банан': [
    5,
    'predmeti/banan.jpg',
    'bukvi/b.png',
    'sound/banan.mp3',
  ],
  'Барабан': [
    7,
    'predmeti/barbaran.jpg',
    'bukvi/b.png',
    'sound/barbaran.mp3',
  ],
  'Бисквита': [
    8,
    'predmeti/biskvita.jpg',
    'bukvi/b.png',
    'sound/biskvita.mp3',
  ],
  'Близалка': [
    8,
    'predmeti/blizalka.jpg',
    'bukvi/b.png',
    'sound/blizalka.mp3',
  ],
  'Бонбон': [
    6,
    'predmeti/bonbon.jpg',
    'bukvi/b.png',
    'sound/bonbon.mp3',
  ],
  'Бос': [
    3,
    'predmeti/bos.jpg',
    'bukvi/b.png',
    'sound/bos.mp3',
  ],
  'Вода': [
    4,
    'predmeti/voda.jpg',
    'bukvi/v.png',
    'sound/voda.mp3',
  ],
  'Врата': [
    5,
    'predmeti/vrata.jpg',
    'bukvi/v.png',
    'sound/vrata.mp3',
  ],
  'Вълна': [
    5,
    'predmeti/valna.jpg',
    'bukvi/v.png',
    'sound/valna.mp3',
  ],
  'Газ': [
    3,
    'predmeti/gaz.jpg',
    'bukvi/g.png',
    'sound/gaz.mp3',
  ],
  'Гараж': [
    5,
    'predmeti/garaj.jpg',
    'bukvi/g.png',
    'sound/garaj.mp3',
  ],
  'Гарван': [
    6,
    'predmeti/garvan.jpg',
    'bukvi/g.png',
    'sound/garvan.mp3',
  ],
  'Гардероб': [
    8,
    'predmeti/garderob.jpg',
    'bukvi/g.png',
    'sound/garderob.mp3',
  ],
  'Гребен': [
    6,
    'predmeti/greben.jpg',
    'bukvi/g.png',
    'sound/greben.mp3',
  ],
  'Грозде': [
    6,
    'predmeti/grozde.jpg',
    'bukvi/g.png',
    'sound/grozde.mp3',
  ],
  'Гъба': [
    4,
    'predmeti/gaba.jpg',
    'bukvi/g.png',
    'sound/gaba.mp3',
  ],
  'Гълъб': [
    5,
    'predmeti/galab.jpg',
    'bukvi/g.png',
    'sound/galab.mp3',
  ],
  'Делфин': [
    6,
    'predmeti/delfin.jpg',
    'bukvi/d.png',
    'sound/delfin.mp3',
  ],
  'Дим': [
    3,
    'predmeti/dim.jpg',
    'bukvi/d.png',
    'sound/dim.mp3',
  ],
  'Диня': [
    4,
    'predmeti/dinq.jpg',
    'bukvi/d.png',
    'sound/dinq.mp3',
  ],
  'Дърво': [
    5,
    'predmeti/darvo.jpg',
    'bukvi/d.png',
    'sound/darvo.mp3',
  ],
  'Елен': [
    4,
    'predmeti/elen.jpg',
    'bukvi/e.png',
    'sound/elen.mp3',
  ],
  'Елха': [
    4,
    'predmeti/elha.jpg',
    'bukvi/e.png',
    'sound/elha.mp3',
  ],
  'Жаба': [
    4,
    'predmeti/jaba.jpg',
    'bukvi/jh.png',
    'sound/jaba.mp3',
  ],
  'Желе': [
    4,
    'predmeti/jele.jpg',
    'bukvi/jh.png',
    'sound/jele.mp3',
  ],
  'Жираф': [
    5,
    'predmeti/jirav.jpg',
    'bukvi/jh.png',
    'sound/jirav.mp3',
  ],
  'Жълто': [
    5,
    'predmeti/jalto.jpg',
    'bukvi/jh.png',
    'sound/jalto.mp3',
  ],
  'Заек': [
    4,
    'predmeti/zaek.jpg',
    'bukvi/z.png',
    'sound/zaek.mp3',
  ],
  'Зар': [
    3,
    'predmeti/zar.jpg',
    'bukvi/z.png',
    'sound/zar.mp3',
  ],
  'Зебра': [
    5,
    'predmeti/zebra.jpg',
    'bukvi/z.png',
    'sound/zebra.mp3',
  ],
  'Изгрев': [
    6,
    'predmeti/izgrev.jpg',
    'bukvi/i.png',
    'sound/izgrev.mp3',
  ],
  'Искра': [
    5,
    'predmeti/iskra.jpg',
    'bukvi/i.png',
    'sound/iskra.mp3',
  ],
  'Йога': [
    4,
    'predmeti/ioga.jpg',
    'bukvi/ii.png',
    'sound/ioga.mp3',
  ],
  'Калинка': [
    7,
    'predmeti/kalinka.jpg',
    'bukvi/k.png',
    'sound/kalinka.mp3',
  ],
  'Камък': [
    5,
    'predmeti/kamak.jpg',
    'bukvi/k.png',
    'sound/kamak.mp3',
  ],
  'Картоф': [
    6,
    'predmeti/kartof.jpg',
    'bukvi/k.png',
    'sound/kartof.mp3',
  ],
  'Катерица': [
    8,
    'predmeti/katerica.jpg',
    'bukvi/k.png',
    'sound/katerica.mp3',
  ],
  'Кенгуру': [
    7,
    'predmeti/kenguru.jpg',
    'bukvi/k.png',
    'sound/kenguru.mp3',
  ],
  'Килим': [
    5,
    'predmeti/kilim.jpg',
    'bukvi/k.png',
    'sound/kilim.mp3',
  ],
  'Китара': [
    6,
    'predmeti/kitara.jpg',
    'bukvi/k.png',
    'sound/kitara.mp3',
  ],
  'Книга': [
    5,
    'predmeti/kniga.jpg',
    'bukvi/k.png',
    'sound/kniga.mp3',
  ],
  'Коза': [
    4,
    'predmeti/koza.jpg',
    'bukvi/k.png',
    'sound/koza.mp3',
  ],
  'Кола': [
    4,
    'predmeti/kola.jpg',
    'bukvi/k.png',
    'sound/kola.mp3',
  ],
  'Колело': [
    6,
    'predmeti/kolelo.jpg',
    'bukvi/k.png',
    'sound/kolelo.mp3',
  ],
  'Кон': [
    3,
    'predmeti/kon.jpg',
    'bukvi/k.png',
    'sound/kon.mp3',
  ],
  'Кораб': [
    5,
    'predmeti/korab.jpg',
    'bukvi/k.png',
    'sound/korab.mp3',
  ],
  'Котка': [
    5,
    'predmeti/kotka.jpg',
    'bukvi/k.png',
    'sound/kotka.mp3',
  ],
  'Кофа': [
    4,
    'predmeti/kofa.jpg',
    'bukvi/k.png',
    'sound/kofa.mp3',
  ],
  'Кутия': [
    5,
    'predmeti/kutiq.jpg',
    'bukvi/k.png',
    'sound/kutiq.mp3',
  ],
  'Куфар': [
    5,
    'predmeti/kufar.jpg',
    'bukvi/k.png',
    'sound/kufar.mp3',
  ],
  'Куче': [
    4,
    'predmeti/kuche.jpg',
    'bukvi/k.png',
    'sound/kuche.mp3',
  ],
  'Кълвач': [
    6,
    'predmeti/kalvach.jpg',
    'bukvi/k.png',
    'sound/kalvach.mp3',
  ],
  'Къща': [
    4,
    'predmeti/kashta.jpg',
    'bukvi/k.png',
    'sound/kashta.mp3',
  ],
  'Лебед': [
    5,
    'predmeti/lebed.jpg',
    'bukvi/l.png',
    'sound/lebed.mp3',
  ],
  'Лисица': [
    6,
    'predmeti/lisica.jpg',
    'bukvi/l.png',
    'sound/lisica.mp3',
  ],
  'Ловец': [
    5,
    'predmeti/lovec.jpg',
    'bukvi/l.png',
    'sound/lovec.mp3',
  ],
  'Лопата': [
    6,
    'predmeti/lopata.jpg',
    'bukvi/l.png',
    'sound/lopata.mp3',
  ],
  'Лук': [
    3,
    'predmeti/luk.jpg',
    'bukvi/l.png',
    'sound/luk.mp3',
  ],
  'Луна': [
    4,
    'predmeti/luna.jpg',
    'bukvi/l.png',
    'sound/luna.mp3',
  ],
  'Маймуна': [
    6,
    'predmeti/maimuna.jpg',
    'bukvi/m.png',
    'sound/maimuna.mp3',
  ],
  'Маса': [
    4,
    'predmeti/masa.jpg',
    'bukvi/m.png',
    'sound/masa.mp3',
  ],
  'Мечка': [
    5,
    'predmeti/mechka.jpg',
    'bukvi/m.png',
    'sound/mechka.mp3',
  ],
  'Миди': [
    4,
    'predmeti/midi.jpg',
    'bukvi/m.png',
    'sound/midi.mp3',
  ],
  // 'Микровълнова': [
  //   12,
  //   'predmeti/mikrovalnova.jpg',
  //   'bukvi/m.png',
  // ],
  'Мишка': [
    5,
    'predmeti/mishka.jpg',
    'bukvi/m.png',
    'sound/mishka.mp3',
  ],
  'Моливник': [
    8,
    'predmeti/molivnik.jpg',
    'bukvi/m.png',
    'sound/molivnik.mp3',
  ],
  'Муха': [
    4,
    'predmeti/muha.jpg',
    'bukvi/m.png',
    'sound/muha.mp3',
  ],
  'Нар': [
    3,
    'predmeti/nar.jpg',
    'bukvi/n.png',
    'sound/nar.mp3',
  ],
  'Ножица': [
    6,
    'predmeti/nojica.jpg',
    'bukvi/n.png',
    'sound/nojica.mp3',
  ],
  'Носорог': [
    7,
    'predmeti/horoskop.jpg',
    'bukvi/n.png',
    'sound/horoskop.mp3',
  ],
  'Нощ': [
    3,
    'predmeti/nosht.jpg',
    'bukvi/n.png',
    'sound/nosht.mp3',
  ],
  'Облак': [
    5,
    'predmeti/oblak.jpg',
    'bukvi/o.png',
    'sound/oblak.mp3',
  ],
  'Октопод': [
    7,
    'predmeti/oktopod.jpg',
    'bukvi/o.png',
    'sound/oktopod.mp3',
  ],
  'Орел': [
    4,
    'predmeti/orel.jpg',
    'bukvi/o.png',
    'sound/orel.mp3',
  ],
  'Охлюв': [
    5,
    'predmeti/ohluv.jpg',
    'bukvi/o.png',
    'sound/ohluv.mp3',
  ],
  'Очила': [
    5,
    'predmeti/ochila.jpg',
    'bukvi/o.png',
    'sound/ochila.mp3',
  ],
  'Памук': [
    5,
    'predmeti/pamuk.jpg',
    'bukvi/p.png',
    'sound/pamuk.mp3',
  ],
  'Пеперуда': [
    8,
    'predmeti/peperuda.jpg',
    'bukvi/p.png',
    'sound/peperuda.mp3',
  ],
  'Перо': [
    4,
    'predmeti/pero.png',
    'bukvi/p.png',
    'sound/pero.mp3',
  ],
  'Петел': [
    5,
    'predmeti/petel.jpg',
    'bukvi/p.png',
    'sound/petel.mp3',
  ],
  'Писмо': [
    5,
    'predmeti/pismo.jpg',
    'bukvi/p.png',
    'sound/pismo.mp3',
  ],
  'Пица': [
    4,
    'predmeti/pica.jpg',
    'bukvi/p.png',
    'sound/pica.mp3',
  ],
  'Плащ': [
    4,
    'predmeti/plasht.jpg',
    'bukvi/p.png',
    'sound/plasht.mp3',
  ],
  'Подарък': [
    7,
    'predmeti/podarak.jpg',
    'bukvi/p.png',
    'sound/podarak.mp3',
  ],
  'Пола': [
    4,
    'predmeti/pola.jpg',
    'bukvi/p.png',
    'sound/pola.mp3',
  ],
  'Поничка': [
    7,
    'predmeti/ponichka.jpg',
    'bukvi/p.png',
    'sound/ponichka.mp3',
  ],
  'Поп': [
    3,
    'predmeti/pop.jpg',
    'bukvi/p.png',
    'sound/pop.mp3',
  ],
  'Портокал': [
    8,
    'predmeti/portokal.jpg',
    'bukvi/p.png',
    'sound/portokal.mp3',
  ],
  'Праг': [
    4,
    'predmeti/prag.jpg',
    'bukvi/p.png',
    'sound/prag.mp3',
  ],
  'Прежда': [
    5,
    'predmeti/prejda.jpg',
    'bukvi/p.png',
    'sound/prejda.mp3',
  ],
  'Пръст': [
    5,
    'predmeti/prast.jpg',
    'bukvi/p.png',
    'sound/prast.mp3',
  ],
  'Пчела': [
    5,
    'predmeti/pchela.jpg',
    'bukvi/p.png',
    'sound/pchela.mp3',
  ],
  'Пън': [
    3,
    'predmeti/pan.jpg',
    'bukvi/p.png',
    'sound/pan.mp3',
  ],
  'Рак': [
    3,
    'predmeti/rak.jpg',
    'bukvi/r.png',
    'sound/rak.mp3',
  ],
  'Ракета': [
    6,
    'predmeti/raketa.jpg',
    'bukvi/r.png',
    'sound/raketa.mp3',
  ],
  'Раница': [
    6,
    'predmeti/ranica.jpg',
    'bukvi/r.png',
    'sound/ranica.mp3',
  ],
  'Риба': [
    4,
    'predmeti/riba.jpg',
    'bukvi/r.png',
    'sound/riba.mp3',
  ],
  'Роза': [
    4,
    'predmeti/roza.jpg',
    'bukvi/r.png',
    'sound/roza.mp3',
  ],
  'Ръка': [
    4,
    'predmeti/raka.jpg',
    'bukvi/r.png',
    'sound/raka.mp3',
  ],
  'Самолет': [
    7,
    'predmeti/samolet.jpg',
    'bukvi/s.png',
    'sound/samolet.mp3',
  ],
  'Сладолед': [
    8,
    'predmeti/sladoled.jpg',
    'bukvi/s.png',
    'sound/sladoled.mp3',
  ],
  'Слънце': [
    6,
    'predmeti/slache.jpg',
    'bukvi/s.png',
    'sound/slache.mp3',
  ],
  'Сок': [
    3,
    'predmeti/sok.jpg',
    'bukvi/s.png',
    'sound/sok.mp3',
  ],
  'Стена': [
    5,
    'predmeti/stena.jpg',
    'bukvi/s.png',
    'sound/stena.mp3',
  ],
  'Страх': [
    5,
    'predmeti/strah.jpg',
    'bukvi/s.png',
    'sound/strah.mp3',
  ],
  'Сърф': [
    4,
    'predmeti/sarf.jpg',
    'bukvi/s.png',
    'sound/sarf.mp3',
  ],
  'Таралеж': [
    7,
    'predmeti/taralej.jpg',
    'bukvi/t.png',
    'sound/taralej.mp3',
  ],
  'Тениска': [
    7,
    'predmeti/teniska.jpg',
    'bukvi/t.png',
    'sound/teniska.mp3',
  ],
  'Тесто': [
    5,
    'predmeti/testo.jpg',
    'bukvi/t.png',
    'sound/testo.mp3',
  ],
  'Тигър': [
    5,
    'predmeti/tigar.jpg',
    'bukvi/t.png',
    'sound/tigar.mp3',
  ],
  'Тикви': [
    5,
    'predmeti/tikvi.jpg',
    'bukvi/t.png',
    'sound/tikvi.mp3',
  ],
  'Топка': [
    5,
    'predmeti/topka.jpg',
    'bukvi/t.png',
    'sound/topka.mp3',
  ],
  'Торта': [
    5,
    'predmeti/torta.jpg',
    'bukvi/t.png',
    'sound/torta.mp3',
  ],
  'Тостер': [
    6,
    'predmeti/toster.jpg',
    'bukvi/t.png',
    'sound/toster.mp3',
  ],
  'Уста': [
    4,
    'predmeti/usta.jpg',
    'bukvi/uu.png',
    'sound/usta.mp3',
  ],
  'Училище': [
    7,
    'predmeti/uchilishte.jpg',
    'bukvi/uu.png',
    'sound/uchilishte.mp3',
  ],
  'Фазан': [
    5,
    'predmeti/fazan.jpg',
    'bukvi/f.png',
    'sound/fazan.mp3',
  ],
  'Факла': [
    5,
    'predmeti/fakla.jpg',
    'bukvi/f.png',
    'sound/fakla.mp3',
  ],
  'Фар': [
    3,
    'predmeti/far.jpg',
    'bukvi/f.png',
    'sound/far.mp3',
  ],
  'Хапче': [
    5,
    'predmeti/hapche.jpg',
    'bukvi/h.png',
    'sound/hapche.mp3',
  ],
  'Хляб': [
    4,
    'predmeti/hlqb.jpg',
    'bukvi/h.png',
    'sound/hlqb.mp3',
  ],
  'Хълм': [
    4,
    'predmeti/halm.jpg',
    'bukvi/h.png',
    'sound/halm.mp3',
  ],
  'Цар': [
    3,
    'predmeti/car.jpg',
    'bukvi/c.png',
    'sound/car.mp3',
  ],
  'Цвете': [
    5,
    'predmeti/cvete.jpg',
    'bukvi/c.png',
    'sound/cvete.mp3',
  ],
  'Цигулка': [
    7,
    'predmeti/cigulka.jpg',
    'bukvi/c.png',
    'sound/cigulka.mp3',
  ],
  'Цип': [
    3,
    'predmeti/cip.jpg',
    'bukvi/c.png',
    'sound/cip.mp3',
  ],
  'Чай': [
    3,
    'predmeti/chai.jpg',
    'bukvi/ch.png',
    'sound/chai.mp3',
  ],
  'Череша': [
    6,
    'predmeti/cheresha.jpg',
    'bukvi/ch.png',
    'sound/cheresha.mp3',
  ],
  'Чорап': [
    5,
    'predmeti/chorap.jpg',
    'bukvi/ch.png',
    'sound/chorap.mp3',
  ],
  'Шал': [
    3,
    'predmeti/shal.jpg',
    'bukvi/sh.png',
    'sound/shal.mp3',
  ],
  'Шапка': [
    5,
    'predmeti/shapka.jpg',
    'bukvi/sh.png',
    'sound/shapka.mp3',
  ],
  'Шишарка': [
    7,
    'predmeti/shisharka.jpg',
    'bukvi/sh.png',
    'sound/shisharka.mp3',
  ],
  'Щит': [
    3,
    'predmeti/shtit.jpg',
    'bukvi/sht.png',
    'sound/shtit.mp3',
  ],
  'Щори': [
    4,
    'predmeti/shtori.jpg',
    'bukvi/sht.png',
    'sound/shtori.mp3',
  ],
  'Щъркел': [
    6,
    'predmeti/shtarkel.jpg',
    'bukvi/sht.png',
    'sound/shtarkel.mp3',
  ],
  'Ъгъл': [
    4,
    'predmeti/agal.jpg',
    'bukvi/aa_a.png',
    'sound/agal.mp3',
  ],
  'Юрган': [
    5,
    'predmeti/urgan.jpg',
    'bukvi/u.png',
    'sound/urgan.mp3',
  ],
  // 'Ютия': [
  //   5,
  //   'predmeti/utiq.jpg',
  //   'bukvi/u.png',
  // ],
  'Ябълка': [
    6,
    'predmeti/qbalka.jpg',
    'bukvi/q.png',
    'sound/qbalka.mp3',
  ],
  'Ягода': [
    5,
    'predmeti/qgoda.jpg',
    'bukvi/q.png',
    'sound/qgoda.mp3',
  ],
  'Язовец': [
    6,
    'predmeti/qzovech.jpg',
    'bukvi/q.png',
    'sound/qzovech.mp3',
  ],
  'Яйце': [
    4,
    'predmeti/qice.jpg',
    'bukvi/q.png',
    'sound/qice.mp3',
  ],
};
